export type SynonymEntry = {
  triggers: string[];
  expansions: string[];
  categorySlugs?: string[];
};

export const SYNONYMS: SynonymEntry[] = [
  {
    triggers: ["cumpleanos", "cumple", "cumples", "aniversario"],
    expansions: [
      "torta",
      "pasteleria",
      "reposteria",
      "candy bar",
      "animacion",
      "fotografia",
      "decoracion",
      "souvenirs",
      "cotillon",
      "eventos",
      "catering",
      "pinata",
      "regalos",
    ],
    categorySlugs: ["eventos-y-catering", "ninos-y-juegos", "alimentos-y-bebidas"],
  },
  {
    triggers: ["comunion", "comuniones", "bautismo", "bautismos", "confirmacion"],
    expansions: [
      "souvenirs",
      "regalos personalizados",
      "imprenta",
      "diseno grafico",
      "decoracion",
      "fotografia",
      "eventos",
      "catering",
      "tarjetas",
      "invitaciones",
    ],
    categorySlugs: ["eventos-y-catering", "diseno-y-oficios"],
  },
  {
    triggers: ["casamiento", "boda", "civil"],
    expansions: [
      "catering",
      "fotografia",
      "video",
      "decoracion",
      "souvenirs",
      "tarjetas",
      "florista",
      "eventos",
      "musica",
      "dj",
    ],
    categorySlugs: ["eventos-y-catering"],
  },
  {
    triggers: ["clases", "clase", "profe", "profesor", "profesora", "apoyo"],
    expansions: [
      "apoyo escolar",
      "profesor particular",
      "matematica",
      "ingles",
      "lengua",
      "fisica",
      "quimica",
      "biologia",
      "lectoescritura",
    ],
    categorySlugs: ["educacion-y-clases"],
  },
  {
    triggers: ["matematica", "matematicas", "algebra", "geometria"],
    expansions: ["matematica", "apoyo escolar", "profesor particular", "secundario", "primario"],
    categorySlugs: ["educacion-y-clases"],
  },
  {
    triggers: ["ingles", "english"],
    expansions: ["ingles", "clases", "apoyo", "examenes", "preparacion"],
    categorySlugs: ["educacion-y-clases"],
  },
  {
    triggers: ["torta", "tortas", "cupcake", "cupcakes", "muffins"],
    expansions: [
      "pasteleria",
      "reposteria",
      "torta tematica",
      "cumpleanos",
      "comunion",
      "candy bar",
      "pasteles",
    ],
    categorySlugs: ["alimentos-y-bebidas", "eventos-y-catering"],
  },
  {
    triggers: ["vianda", "viandas", "comida", "almuerzo", "menu"],
    expansions: ["viandas", "catering", "comida casera", "menu saludable", "tupper", "delivery"],
    categorySlugs: ["alimentos-y-bebidas", "eventos-y-catering"],
  },
  {
    triggers: ["aire", "acondicionado", "split", "refrigeracion"],
    expansions: [
      "aire acondicionado",
      "tecnico",
      "refrigeracion",
      "instalacion",
      "service",
      "mantenimiento",
    ],
    categorySlugs: ["servicios-del-hogar", "tecnologia"],
  },
  {
    triggers: ["plomero", "plomeria", "cano", "canio"],
    expansions: ["plomeria", "destapaciones", "gas", "agua", "mantenimiento"],
    categorySlugs: ["servicios-del-hogar"],
  },
  {
    triggers: ["electricista", "electricidad", "tablero"],
    expansions: ["electricista", "instalaciones", "tablero", "iluminacion", "mantenimiento"],
    categorySlugs: ["servicios-del-hogar"],
  },
  {
    triggers: ["pintor", "pintura", "pintar"],
    expansions: ["pintor", "pintura", "albanil", "refaccion"],
    categorySlugs: ["servicios-del-hogar"],
  },
  {
    triggers: ["limpieza", "limpiar", "domestica"],
    expansions: ["limpieza", "domestica", "mantenimiento", "hogar"],
    categorySlugs: ["servicios-del-hogar"],
  },
  {
    triggers: ["jardin", "jardinero", "cesped", "poda"],
    expansions: ["jardineria", "parquizacion", "poda", "cesped"],
    categorySlugs: ["servicios-del-hogar"],
  },
  {
    triggers: ["psicopedagoga", "psicopedagogia", "fonoaudiologa", "fono", "psicologa", "psicologo"],
    expansions: [
      "psicopedagogia",
      "fonoaudiologia",
      "psicologia",
      "salud",
      "apoyo profesional",
      "ninos",
    ],
    categorySlugs: ["salud-y-bienestar", "educacion-y-clases"],
  },
  {
    triggers: ["nutricionista", "dieta", "alimentacion saludable"],
    expansions: ["nutricionista", "salud", "alimentacion", "dieta", "saludable"],
    categorySlugs: ["salud-y-bienestar"],
  },
  {
    triggers: ["kinesiologa", "kinesiologo", "kinesiologia", "kine"],
    expansions: ["kinesiologia", "rehabilitacion", "salud", "lesiones"],
    categorySlugs: ["salud-y-bienestar"],
  },
  {
    triggers: ["pilates", "yoga", "gimnasia", "entrenamiento"],
    expansions: ["pilates", "yoga", "movimiento", "entrenamiento", "salud", "actividad fisica"],
    categorySlugs: ["salud-y-bienestar"],
  },
  {
    triggers: ["souvenir", "souvenirs", "recuerdos"],
    expansions: [
      "souvenirs",
      "regalos personalizados",
      "imprenta",
      "sublimacion",
      "diseno grafico",
      "cotillon",
      "decoracion",
    ],
    categorySlugs: ["diseno-y-oficios", "eventos-y-catering"],
  },
  {
    triggers: ["regalo", "regalos", "presente"],
    expansions: [
      "regalos personalizados",
      "artesanias",
      "diseno",
      "imprenta",
      "sublimacion",
      "decoracion",
      "manualidades",
    ],
    categorySlugs: ["diseno-y-oficios", "ninos-y-juegos"],
  },
  {
    triggers: ["fotografo", "fotografa", "fotografia", "fotos"],
    expansions: ["fotografia", "fotografo", "eventos", "books", "retratos"],
    categorySlugs: ["eventos-y-catering", "diseno-y-oficios"],
  },
  {
    triggers: ["ropa", "indumentaria", "remera", "vestido"],
    expansions: ["indumentaria", "ropa", "uniformes", "calzado", "accesorios"],
    categorySlugs: ["indumentaria-y-accesorios"],
  },
  {
    triggers: ["uniforme", "uniformes", "guardapolvo"],
    expansions: ["uniformes", "indumentaria", "ropa escolar", "guardapolvo"],
    categorySlugs: ["indumentaria-y-accesorios"],
  },
  {
    triggers: ["pc", "computadora", "notebook", "laptop", "celular", "telefono"],
    expansions: [
      "reparacion",
      "tecnologia",
      "soporte tecnico",
      "instalacion",
      "service",
      "computadoras",
      "notebooks",
    ],
    categorySlugs: ["tecnologia"],
  },
  {
    triggers: ["pagina web", "sitio web", "web", "ecommerce", "tienda online"],
    expansions: [
      "diseno web",
      "desarrollo",
      "programacion",
      "tienda online",
      "tecnologia",
      "marketing",
    ],
    categorySlugs: ["tecnologia", "diseno-y-oficios", "servicios-profesionales"],
  },
  {
    triggers: ["contadora", "contador", "impuestos", "monotributo", "afip"],
    expansions: ["contabilidad", "impuestos", "monotributo", "asesoria", "servicios profesionales"],
    categorySlugs: ["servicios-profesionales"],
  },
  {
    triggers: ["abogada", "abogado", "legal", "juicio"],
    expansions: ["abogada", "asesoria legal", "juicios", "servicios profesionales"],
    categorySlugs: ["servicios-profesionales"],
  },
  {
    triggers: ["peluqueria", "peluquera", "corte", "cabello", "tintura"],
    expansions: ["peluqueria", "belleza", "corte", "cabello", "tintura"],
    categorySlugs: ["belleza-y-cuidado-personal"],
  },
  {
    triggers: ["manicura", "unas", "pedicura"],
    expansions: ["manicura", "pedicura", "unas", "belleza", "estetica"],
    categorySlugs: ["belleza-y-cuidado-personal"],
  },
  {
    triggers: ["maquillaje", "maquilladora"],
    expansions: ["maquillaje", "belleza", "eventos", "novia", "fiesta"],
    categorySlugs: ["belleza-y-cuidado-personal"],
  },
  {
    triggers: ["mueble", "muebles", "carpinteria", "carpintero", "madera"],
    expansions: ["muebles a medida", "carpinteria", "madera", "restauracion"],
    categorySlugs: ["servicios-del-hogar", "diseno-y-oficios"],
  },
  {
    triggers: ["juguete", "juguetes", "juego"],
    expansions: ["juguetes", "juguetes artesanales", "regalos", "ninos", "madera", "tela"],
    categorySlugs: ["ninos-y-juegos"],
  },
];

export const STOPWORDS = new Set<string>([
  "a",
  "al",
  "algo",
  "alguien",
  "algun",
  "alguna",
  "alguno",
  "ante",
  "antes",
  "asi",
  "bien",
  "bueno",
  "buena",
  "buscar",
  "buscando",
  "busco",
  "cerca",
  "como",
  "con",
  "del",
  "de",
  "donde",
  "el",
  "ella",
  "ellas",
  "ellos",
  "en",
  "entre",
  "es",
  "esa",
  "ese",
  "eso",
  "esta",
  "estan",
  "este",
  "esto",
  "estoy",
  "fue",
  "ha",
  "hace",
  "hacer",
  "hago",
  "hay",
  "la",
  "las",
  "le",
  "les",
  "lo",
  "los",
  "me",
  "mi",
  "mis",
  "mucho",
  "muy",
  "necesitamos",
  "necesitar",
  "necesito",
  "no",
  "nos",
  "o",
  "para",
  "pero",
  "por",
  "porque",
  "que",
  "quien",
  "quiero",
  "se",
  "si",
  "soy",
  "su",
  "sus",
  "tan",
  "te",
  "tengo",
  "ti",
  "tu",
  "tus",
  "un",
  "una",
  "unas",
  "uno",
  "unos",
  "y",
  "ya",
  "yo",
]);

export const SEARCH_WEIGHTS = {
  textRank: 2.5,
  tagOverlap: 1.5,
  categoryMatch: 3,
  categoryNameMatch: 1.5,
  zoneMatch: 2,
  featured: 1,
  recencyDays: 90,
  recencyBoost: 0.6,
  minScore: 0.2,
} as const;
